# Generated by Django 5.2.7 on 2025-11-03 16:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='ファイル名')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='ファイルパス')),
                ('status', models.CharField(choices=[('pending', '処理待ち'), ('processing', '処理中'), ('completed', '完了'), ('error', 'エラー')], default='pending', max_length=20, verbose_name='ステータス')),
                ('total_rows', models.IntegerField(default=0, verbose_name='総行数')),
                ('active_subscriptions', models.IntegerField(default=0, verbose_name='継続ユーザー数')),
                ('matched_count', models.IntegerField(default=0, verbose_name='突合成功数')),
                ('error_message', models.TextField(blank=True, verbose_name='エラーメッセージ')),
                ('uploaded_by', models.CharField(blank=True, max_length=100, verbose_name='アップロード者')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='アップロード日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'CSVアップロード',
                'verbose_name_plural': 'CSVアップロード',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='メールアドレス')),
                ('subscription_id', models.CharField(help_text='サブスクサービスの一意なID', max_length=100, unique=True, verbose_name='サブスクリプションID')),
                ('is_active', models.BooleanField(default=True, help_text='サブスクリプションが有効かどうか', verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'サブスクユーザー',
                'verbose_name_plural': 'サブスクユーザー',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalonApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='姓')),
                ('first_name', models.CharField(max_length=50, verbose_name='名')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='メールアドレス')),
                ('subscription_id', models.CharField(blank=True, help_text='（非推奨：CSV突合で使用）', max_length=100, null=True, verbose_name='サブスクリプションID')),
                ('subscription_verified', models.BooleanField(default=False, help_text='サブスクサービスの利用確認が完了したか', verbose_name='サブスク確認済み')),
                ('match_method', models.CharField(blank=True, choices=[('email_and_name', 'メール+名前'), ('email_only', 'メールのみ'), ('name_only', '名前のみ'), ('manual', '手動'), ('', '未突合')], default='', help_text='突合に使用した方法', max_length=20, verbose_name='突合方法')),
                ('matched_at', models.DateTimeField(blank=True, help_text='突合が完了した日時', null=True, verbose_name='突合日時')),
                ('match_notes', models.TextField(blank=True, help_text='突合時のメモ（不一致理由など）', verbose_name='突合備考')),
                ('status', models.CharField(choices=[('pending', '審査中'), ('verified', '確認済み'), ('approved', '承認済み'), ('rejected', '拒否'), ('completed', 'アクセス付与済み')], default='pending', max_length=20, verbose_name='ステータス')),
                ('access_granted', models.BooleanField(default=False, verbose_name='アクセス付与済み')),
                ('access_granted_at', models.DateTimeField(blank=True, null=True, verbose_name='アクセス付与日時')),
                ('access_token', models.CharField(blank=True, help_text='オンラインサロンへのアクセストークン', max_length=200, verbose_name='アクセストークン')),
                ('notes', models.TextField(blank=True, help_text='内部メモ', verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申し込み日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('csv_upload', models.ForeignKey(blank=True, help_text='突合に使用したCSV', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='application.csvupload', verbose_name='関連CSVアップロード')),
                ('subscription_user', models.ForeignKey(blank=True, help_text='確認されたサブスクユーザー情報', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='application.subscriptionuser', verbose_name='関連サブスクユーザー')),
            ],
            options={
                'verbose_name': 'サロン申し込み',
                'verbose_name_plural': 'サロン申し込み',
                'ordering': ['-created_at'],
            },
        ),
    ]
