# Generated by Django 5.2.7 on 2025-11-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonapplication',
            name='access_revocation_required',
            field=models.BooleanField(default=False, help_text='CSV突合により「継続」以外と突合され、アクセス権の剥奪が必要な場合にマークされます', verbose_name='アクセス剥奪必要'),
        ),
        migrations.AddField(
            model_name='salonapplication',
            name='access_revocation_required_at',
            field=models.DateTimeField(blank=True, help_text='アクセス剥奪必要フラグが立てられた日時', null=True, verbose_name='アクセス剥奪必要マーク日時'),
        ),
        migrations.AddField(
            model_name='salonapplication',
            name='access_revoked_at',
            field=models.DateTimeField(blank=True, help_text='実際にアクセス権が剥奪された日時', null=True, verbose_name='アクセス剥奪実行日時'),
        ),
    ]
