# Generated by Django 5.2.7 on 2025-11-04 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_salonapplication_access_revocation_required_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionuser',
            options={'ordering': ['-created_at'], 'verbose_name': '定期購入ユーザー', 'verbose_name_plural': '定期購入ユーザー'},
        ),
        migrations.RemoveField(
            model_name='salonapplication',
            name='access_token',
        ),
        migrations.AlterField(
            model_name='salonapplication',
            name='subscription_user',
            field=models.ForeignKey(blank=True, help_text='確認された定期購入ユーザー情報', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='application.subscriptionuser', verbose_name='関連定期購入ユーザー'),
        ),
        migrations.AlterField(
            model_name='salonapplication',
            name='subscription_verified',
            field=models.BooleanField(default=False, help_text='Joy Journeyの定期購入の利用確認が完了したか', verbose_name='定期購入確認済み'),
        ),
        migrations.AlterField(
            model_name='subscriptionuser',
            name='subscription_id',
            field=models.CharField(help_text='Joy Journeyの定期購入の一意なID', max_length=100, unique=True, verbose_name='サブスクリプションID'),
        ),
    ]
