# Generated by Django 5.2.7 on 2025-11-04 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_remove_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonapplication',
            name='discord_account_name',
            field=models.CharField(blank=True, help_text='サロンへのゲストアクセス後に報告されたDiscordアカウント名', max_length=100, verbose_name='Discordアカウント名'),
        ),
        migrations.AddField(
            model_name='salonapplication',
            name='discord_account_submitted_at',
            field=models.DateTimeField(blank=True, help_text='Discordアカウント名が入力された日時', null=True, verbose_name='Discordアカウント名入力日時'),
        ),
    ]
