# Generated by Django 5.2.7 on 2025-11-04 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_add_discord_account_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonapplication',
            name='discord_display_name',
            field=models.CharField(blank=True, help_text='Discordの表示名（日本語可）', max_length=100, verbose_name='Discord表示名'),
        ),
        migrations.AddField(
            model_name='salonapplication',
            name='discord_username',
            field=models.CharField(blank=True, help_text='Discordのアカウント名（username#1234形式、日本語可）', max_length=100, verbose_name='Discordアカウント名'),
        ),
        migrations.AlterField(
            model_name='salonapplication',
            name='discord_account_name',
            field=models.CharField(blank=True, help_text='（非推奨：discord_display_nameとdiscord_usernameを使用してください）', max_length=100, verbose_name='Discordアカウント名（旧）'),
        ),
    ]
