# Generated by Django 5.2.7 on 2025-11-04 05:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_add_discord_display_name_and_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='姓')),
                ('first_name', models.CharField(max_length=50, verbose_name='名')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='メールアドレス')),
                ('subscription_verified', models.BooleanField(default=False, help_text='Joy Journeyの定期購入の利用確認が完了したか', verbose_name='定期購入確認済み')),
                ('match_method', models.CharField(blank=True, choices=[('email_and_name', 'メール+名前'), ('email_only', 'メールのみ'), ('name_only', '名前のみ'), ('manual', '手動'), ('', '未突合')], default='', help_text='突合に使用した方法', max_length=20, verbose_name='突合方法')),
                ('matched_at', models.DateTimeField(blank=True, help_text='突合が完了した日時', null=True, verbose_name='突合日時')),
                ('match_notes', models.TextField(blank=True, help_text='突合時のメモ（不一致理由など）', verbose_name='突合備考')),
                ('status', models.CharField(choices=[('pending', '審査中'), ('verified', '確認済み'), ('approved', '承認済み'), ('rejected', '拒否'), ('completed', '値引き適用済み')], default='pending', max_length=20, verbose_name='ステータス')),
                ('discount_applied', models.BooleanField(default=False, verbose_name='値引き適用済み')),
                ('discount_applied_at', models.DateTimeField(blank=True, null=True, verbose_name='値引き適用日時')),
                ('notes', models.TextField(blank=True, help_text='内部メモ', verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申請日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('csv_upload', models.ForeignKey(blank=True, help_text='突合に使用したCSV', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_applications', to='application.csvupload', verbose_name='関連CSVアップロード')),
                ('subscription_user', models.ForeignKey(blank=True, help_text='確認された定期購入ユーザー情報', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_applications', to='application.subscriptionuser', verbose_name='関連定期購入ユーザー')),
            ],
            options={
                'verbose_name': '値引き申請',
                'verbose_name_plural': '値引き申請',
                'ordering': ['-created_at'],
            },
        ),
    ]
