# Generated by Django 5.2.7 on 2025-11-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_add_discount_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountapplication',
            name='discord_account_submitted_at',
            field=models.DateTimeField(blank=True, help_text='Discordアカウント名が入力された日時', null=True, verbose_name='Discordアカウント名入力日時'),
        ),
        migrations.AddField(
            model_name='discountapplication',
            name='discord_display_name',
            field=models.CharField(blank=True, help_text='Discordの表示名（日本語可）', max_length=100, verbose_name='Discord表示名'),
        ),
        migrations.AddField(
            model_name='discountapplication',
            name='discord_username',
            field=models.CharField(blank=True, help_text='Discordのアカウント名（username#1234形式、日本語可）', max_length=100, verbose_name='Discordアカウント名'),
        ),
    ]
