# Generated by Django 5.2.7 on 2025-11-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_add_discord_to_discount_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvupload',
            name='access_revocation_count',
            field=models.IntegerField(default=0, help_text='アクセス権付与済みとCSVの突合で剥奪が必要と判定された件数', verbose_name='アクセス権剥奪必要件数'),
        ),
        migrations.AddField(
            model_name='csvupload',
            name='discount_match_count',
            field=models.IntegerField(default=0, help_text='値引き申請とCSVの突合成功数', verbose_name='値引き申請突合成功数'),
        ),
        migrations.AddField(
            model_name='csvupload',
            name='discount_revocation_count',
            field=models.IntegerField(default=0, help_text='値引き適用済みとCSVの突合で剥奪が必要と判定された件数', verbose_name='値引き剥奪必要件数'),
        ),
        migrations.AddField(
            model_name='csvupload',
            name='salon_match_count',
            field=models.IntegerField(default=0, help_text='夜遊びサロン利用申請とCSVの突合成功数', verbose_name='サロン申請突合成功数'),
        ),
        migrations.AddField(
            model_name='discountapplication',
            name='discount_revocation_required',
            field=models.BooleanField(default=False, help_text='CSV突合により「継続」以外と突合され、値引きの剥奪が必要な場合にマークされます', verbose_name='値引き剥奪必要'),
        ),
        migrations.AddField(
            model_name='discountapplication',
            name='discount_revocation_required_at',
            field=models.DateTimeField(blank=True, help_text='値引き剥奪必要フラグが立てられた日時', null=True, verbose_name='値引き剥奪必要マーク日時'),
        ),
        migrations.AddField(
            model_name='discountapplication',
            name='discount_revoked_at',
            field=models.DateTimeField(blank=True, help_text='実際に値引きが剥奪された日時', null=True, verbose_name='値引き剥奪実行日時'),
        ),
        migrations.AlterField(
            model_name='csvupload',
            name='matched_count',
            field=models.IntegerField(default=0, help_text='（非推奨：各突合種類別の件数を使用してください）', verbose_name='突合成功数'),
        ),
    ]
